Updates for custom image

diff --git a/task/task_pr_create_promotion.yml b/task/task_pr_create_promotion.yml
--- a/task/task_pr_create_promotion.yml
+++ b/task/task_pr_create_promotion.yml
@@ -16,38 +16,60 @@ spec:
     - name: branchName
       type: string
       description: The name of the new branch to create for the PR
-  workspaces:
-    - name: git-credentials
-      description: Workspace to hold credentials for Git and GitHub API
   steps:
-    - name: clone-repo
-      image: alpine/git
+    - name: update-and-create-pr
+      image: guidoffm/yq-git
+      volumeMounts:
+        - name: repo-volume
+          mountPath: /workspace/repo
+      securityContext:
+        allowPrivilegeEscalation: false
+        runAsNonRoot: true
+        runAsUser: 1001030000
+        capabilities:
+          drop:
+            - ALL
+        seccompProfile:
+          type: RuntimeDefault
+      env:
+        - name: GITHUB_TOKEN
+          valueFrom:
+            secretKeyRef:
+              name: diego-secrets
+              key: GITHUB_TOKEN
       script: |
-        git clone $(params.repoUrl) /workspace/repo
+        # Update packages and install curl
+        apt-get update && apt-get install -y curl
 
-    - name: update-yaml
-      image: mikefarah/yq
-      script: |
-        yq eval '.resourceTemplates[] | select(.name == "aws-vpce-operator-stage-sectors").targets[] | select(.name == "aws-vpce-operator-stage-us-west-2-canary").ref = strenv(imagetag)' -i /workspace/repo/$(params.filePath)
+        # Clone the repository with token authentication
+        REPO_URL_WITH_TOKEN=$(echo "$(params.repoUrl)" | sed "s|//|//${GITHUB_TOKEN}@|")
+        if ! git clone $REPO_URL_WITH_TOKEN /workspace/repo; then
+          echo "Cloning failed"
+          exit 1
+        fi
+        echo "Cloning successful"
 
-    - name: create-branch-commit
-      image: alpine/git
-      # In the final iteration of this task, a bot account will be used to commit and create the PR
-      script: |
+        # Navigate to the repository
         cd /workspace/repo
+
+        # Configure Git for the repository
         git config user.email "dsantama@redhat.com"
         git config user.name "MrSantamaria"
+
+        # Update YAML file
+        yq eval '.resourceTemplates[] | select(.name == "aws-vpce-operator-stage-sectors").targets[] | select(.name == "aws-vpce-operator-stage-us-west-2-canary").ref = "$(params.imagetag)"' -i $(params.filePath)
+        cat $(params.filePath)
+
+        # Create new branch and commit changes
         git checkout -b $(params.branchName)
         git add $(params.filePath)
         git commit -m "Update ref value for aws-vpce-operator-stage-us-west-2-canary"
 
-    - name: push-and-create-pr
-      image: curlimages/curl
-      script: |
-        cd /workspace/repo
-        # Push the branch
+        # Set remote URL with token authentication for push
+        git remote set-url origin $REPO_URL_WITH_TOKEN
+
+        # Push changes and create a pull request
         git push origin $(params.branchName)
-        # Create a pull request
         PR_DATA=$(cat <<EOF
         {
           "title": "Update ref for aws-vpce-operator-stage-us-west-2-canary",
@@ -57,12 +79,9 @@ spec:
         }
         EOF
         )
-        curl -X POST \
-          -H "Authorization: token $(cat $(workspaces.git-credentials.path)/github-token)" \
-          -H "Accept: application/vnd.github.v3+json" \
-          https://api.github.com/repos/MrSantamaria/tekton-poc/pulls \
-          -d "$PR_DATA"
+        curl -X POST -H "Authorization: token $GITHUB_TOKEN" \
+        -H "Accept: application/vnd.github.v3+json" \
+        https://api.github.com/repos/MrSantamaria/tekton-poc/pulls -d "$PR_DATA"
   volumes:
-    - name: git-credentials
-      secret:
-        secretName: diego-secrets
+    - name: repo-volume
+      emptyDir: {}
